<?php

namespace AppBundle\Repository;

/**
 * AmbitosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmbitosRepository extends \Doctrine\ORM\EntityRepository
{
}
