<?php

namespace AppBundle\Repository;

/**
 * IndicadoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicadoresRepository extends \Doctrine\ORM\EntityRepository
{
}
